### ISSUE TITLE
Admission webhook denies requests for docker pull secrets that aren't managed by it

### ISSUE THREAD

**Issue by cbui** [zak905/kube-ecr-secrets-operator#2]
Hi, I'm getting an `admission webhook denied the request: Secret <secret> not found` when trying to pull pods that belong in Dockerhub and not ECR. Can pods pulling from Dockerhub and ECR coexist?

**Comment by zak905** [comment]
Hi @cbui, I have just tested now, and I was not able to reproduce the error, both docker hub and ECR are working along side. Did you create the secret with the AWS access as mentionned here https://github.com/zak905/kube-ecr-secrets-operator/tree/master/chart#installation-and-usage ?

If you can provide some example manifests that reproduce the issue, I can try to debug further

**Comment by zak905** [comment]
@cbui have you been able to resolve the issue ?

**Comment by cbui** [comment]
I have not; I ended up going with another solution. I appreciate your support.

**Comment by zak905** [comment]
Welcome. For the sake of sharing, would you be able to provide an example yaml that can reproduce the issue. That would be helpful, because other users may also be concerned
